title: Cloudychomes Rabbit Hole
email: coudychomes@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Breaking away from the main stream lies, Tackling the hard questions one at a time!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
gab_username: cloudychomes
github_username:  cloudychomes

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

minima:
  social_links:
    - platform: gab  # same as SVG filename.
      user_url: "https://gab.com/cloudychomes"  # URL of profile page.
      title:  My profile at gab.com  # Optional. Text displayed on hovering over link.
